### ISSUE TITLE
WebGL Error with Unity 2021.2.11f1

### ISSUE THREAD

**Issue by caiocabralbr** [ethereum-boilerplate/web3-unity-boilerplate#56]
`Build Benchmark.loader.js:70 exception thrown: RuntimeError: unreachable,RuntimeError: unreachable
    at il2cpp::vm::Exception::Raise(Il2CppException*, MethodInfo*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[2270]:0x19ef03)
    at il2cpp_codegen_raise_exception(Exception_t*, MethodInfo*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[2594]:0x1aaebd)
    at Uri_CreateThis_m522F36D576D9A8803410439127DB32837331BA3A (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[82415]:0x13afe26)
    at Uri__ctor_m6CA436E6AD2768A121FA851CBEEFA3623E849D3A (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[82414]:0x13afceb)
    at Conversion_WebUriToWsURi_m6E98DF69EF4EEAA7C671669EC7244C4F69382183 (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[82794]:0x13ccd62)
    at MoralisService_1__ctor_m7835197D0FC3D5BF182DDA6E92858756AEFA92D7_gshared (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[20616]:0x5959f8)
    at MoralisService_1__ctor_m050DC98E983E8ACF0E5E6037366A2A83CEA9AD1F_gshared (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[20615]:0x595781)
    at MoralisClient__ctor_m4F0AA3563928C5F865FF7BB73533F25112610E36 (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[82784]:0x13cc7d5)
    at dynCall_viiiiii (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[190123]:0x2f8a3d0)
    at http://localhost:1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viiiiii (http://localhost:1090/Build/Build%20Benchmark.framework.js:16797:3)
    at U3CInitializeU3Ed__14_MoveNext_mA551FD18F0C30BDE69A595A37BB0A47C8B924FD7 (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[57490]:0xe57391)
    at InterfaceActionInvoker0::Invoke(unsigned short, Il2CppClass*, Il2CppObject*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[128461]:0x1c51c03)
    at AsyncUniTaskMethodBuilder_Start_TisU3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE_m60A6D5A843E971E0DDD4DB1AD4FC23F49BA8BD45_inline(AsyncUniTaskMethodBuilder_t490751EC621C472E098B12103AF16BC549912BB0*, U3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE**, MethodInfo const*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[8200]:0x2e3743)
    at MoralisInterface_Initialize_m9A5ACBCB2BA5E9377CE02A3C14F575E6BA831958 (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[57469]:0xe5585a)
    at dynCall_viiiiiiii (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[190157]:0x2f8a636)
    at http://localhost:1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viiiiiiii (http://localhost:1090/Build/Build%20Benchmark.framework.js:16973:3)
    at U3CInitializeU3Ed__9_MoveNext_m08C7C710BEE6AE7FB39A68C28DDF4F16902C3577 (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[57468]:0xe55386)
    at InterfaceActionInvoker0::Invoke(unsigned short, Il2CppClass*, Il2CppObject*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[128461]:0x1c51c03)
    at AsyncUniTaskMethodBuilder_Start_TisU3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE_m60A6D5A843E971E0DDD4DB1AD4FC23F49BA8BD45_inline(AsyncUniTaskMethodBuilder_t490751EC621C472E098B12103AF16BC549912BB0*, U3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE**, MethodInfo const*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[8200]:0x2e3743)
    at MoralisController_Initialize_mE34C1576D8FF0EE694FA8A20A8D58EF90FC557CF (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[57467]:0xe550a9)
    at dynCall_viii (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[190126]:0x2f8a400)
    at http://localhost:1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viii (http://localhost:1090/Build/Build%20Benchmark.framework.js:16665:3)
    at U3CStartU3Ed__9_MoveNext_m1C1D7CB4810F671C1D26959815F9108AE2148AEB (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[59333]:0xeceda6)
    at InterfaceActionInvoker0::Invoke(unsigned short, Il2CppClass*, Il2CppObject*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[128461]:0x1c51c03)
    at dynCall_viii (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[190126]:0x2f8a400)
    at http://localhost:1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viii (http://localhost:1090/Build/Build%20Benchmark.framework.js:16665:3)
    at AsyncVoidMethodBuilder_Start_TisRuntimeObject_m3CA145CBB6CFE8B4ADD6148BF98E85899F95DCEA_gshared (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[74678]:0x11f2edf)
    at AsyncVoidMethodBuilder_Start_TisU3CCompleteOpenU3Ed__24_t4E8DD01DC9B1058D072BBAC6EAD09F2B9E8A0DC3_m7E5D77D3538F885CD11D731DBCC76C02EB14CAF4(AsyncVoidMethodBuilder_t253E37B63E7E7B504878AE6563347C147F98EF2D*, U3CCompleteOpenU3Ed__24_t4E8DD01DC9B1058D072BBAC6EAD09F2B9E8A0DC3**, MethodInfo const*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[10628]:0x34ef41)
    at MainMenuScript_Start_mC1D05E15D183A59D0A7AB8AB22E0AA1BBFD1F78F (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[59322]:0xece292)
    at RuntimeInvoker_TrueVoid_t4861ACF8F4594C3437BB48B6E56783494B843915(void (*)(), MethodInfo const*, void*, void**, void*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[166028]:0x243412d)
    at il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[169479]:0x247c720)
    at dynCall_iiii (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[190119]:0x2f8a39a)
    at http://localhost:1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_iiii (http://localhost:1090/Build/Build%20Benchmark.framework.js:16687:10)
    at il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[169451]:0x247bad1)
    at il2cpp_runtime_invoke (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[169528]:0x247def6)
    at ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[187249]:0x2ea4743)
    at MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[187188]:0x2e9f4da)
    at MonoBehaviour::DelayedStartCall(Object*, void*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[187202]:0x2ea0c24)
    at DelayedCallManager::Update(int) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[172355]:0x2522cbb)
    at InitPlayerLoopCallbacks()::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward() (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[186945]:0x2e7baef)
    at ExecutePlayerLoop(NativePlayerLoopSystem*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[172192]:0x251304c)
    at ExecutePlayerLoop(NativePlayerLoopSystem*) (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[172192]:0x25130e8)
    at MainLoop() (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[184761]:0x2d2fbf9)
    at dynCall_v (http://localhost:1090/Build/Build%20Benchmark.wasm:wasm-function[190115]:0x2f8a35f)
    at http://localhost:1090/Build/Build%20Benchmark.framework.js:1055:20
printErr @ Build Benchmark.loader.js:70
`

`Uncaught RuntimeError: unreachable
    at il2cpp::vm::Exception::Raise(Il2CppException*, MethodInfo*) (:1090/Build/Build%20Benchmark.wasm)
    at il2cpp_codegen_raise_exception(Exception_t*, MethodInfo*) (:1090/Build/Build%20Benchmark.wasm)
    at Uri_CreateThis_m522F36D576D9A8803410439127DB32837331BA3A (:1090/Build/Build%20Benchmark.wasm)
    at Uri__ctor_m6CA436E6AD2768A121FA851CBEEFA3623E849D3A (:1090/Build/Build%20Benchmark.wasm)
    at Conversion_WebUriToWsURi_m6E98DF69EF4EEAA7C671669EC7244C4F69382183 (:1090/Build/Build%20Benchmark.wasm)
    at MoralisService_1__ctor_m7835197D0FC3D5BF182DDA6E92858756AEFA92D7_gshared (:1090/Build/Build%20Benchmark.wasm)
    at MoralisService_1__ctor_m050DC98E983E8ACF0E5E6037366A2A83CEA9AD1F_gshared (:1090/Build/Build%20Benchmark.wasm)
    at MoralisClient__ctor_m4F0AA3563928C5F865FF7BB73533F25112610E36 (:1090/Build/Build%20Benchmark.wasm)
    at dynCall_viiiiii (:1090/Build/Build%20Benchmark.wasm)
    at :1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viiiiii (:1090/Build/Build%20Benchmark.framework.js:16797:3)
    at U3CInitializeU3Ed__14_MoveNext_mA551FD18F0C30BDE69A595A37BB0A47C8B924FD7 (:1090/Build/Build%20Benchmark.wasm)
    at InterfaceActionInvoker0::Invoke(unsigned short, Il2CppClass*, Il2CppObject*) (:1090/Build/Build%20Benchmark.wasm)
    at AsyncUniTaskMethodBuilder_Start_TisU3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE_m60A6D5A843E971E0DDD4DB1AD4FC23F49BA8BD45_inline(AsyncUniTaskMethodBuilder_t490751EC621C472E098B12103AF16BC549912BB0*, U3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE**, MethodInfo const*) (:1090/Build/Build%20Benchmark.wasm)
    at MoralisInterface_Initialize_m9A5ACBCB2BA5E9377CE02A3C14F575E6BA831958 (:1090/Build/Build%20Benchmark.wasm)
    at dynCall_viiiiiiii (:1090/Build/Build%20Benchmark.wasm)
    at :1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viiiiiiii (:1090/Build/Build%20Benchmark.framework.js:16973:3)
    at U3CInitializeU3Ed__9_MoveNext_m08C7C710BEE6AE7FB39A68C28DDF4F16902C3577 (:1090/Build/Build%20Benchmark.wasm)
    at InterfaceActionInvoker0::Invoke(unsigned short, Il2CppClass*, Il2CppObject*) (:1090/Build/Build%20Benchmark.wasm)
    at AsyncUniTaskMethodBuilder_Start_TisU3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE_m60A6D5A843E971E0DDD4DB1AD4FC23F49BA8BD45_inline(AsyncUniTaskMethodBuilder_t490751EC621C472E098B12103AF16BC549912BB0*, U3CTransferAsyncU3Ed__44_tE1EC3CFE689D715ACB9A03FE16F97FBCC9B889EE**, MethodInfo const*) (:1090/Build/Build%20Benchmark.wasm)
    at MoralisController_Initialize_mE34C1576D8FF0EE694FA8A20A8D58EF90FC557CF (:1090/Build/Build%20Benchmark.wasm)
    at dynCall_viii (:1090/Build/Build%20Benchmark.wasm)
    at :1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viii (:1090/Build/Build%20Benchmark.framework.js:16665:3)
    at U3CStartU3Ed__9_MoveNext_m1C1D7CB4810F671C1D26959815F9108AE2148AEB (:1090/Build/Build%20Benchmark.wasm)
    at InterfaceActionInvoker0::Invoke(unsigned short, Il2CppClass*, Il2CppObject*) (:1090/Build/Build%20Benchmark.wasm)
    at dynCall_viii (:1090/Build/Build%20Benchmark.wasm)
    at :1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_viii (:1090/Build/Build%20Benchmark.framework.js:16665:3)
    at AsyncVoidMethodBuilder_Start_TisRuntimeObject_m3CA145CBB6CFE8B4ADD6148BF98E85899F95DCEA_gshared (:1090/Build/Build%20Benchmark.wasm)
    at AsyncVoidMethodBuilder_Start_TisU3CCompleteOpenU3Ed__24_t4E8DD01DC9B1058D072BBAC6EAD09F2B9E8A0DC3_m7E5D77D3538F885CD11D731DBCC76C02EB14CAF4(AsyncVoidMethodBuilder_t253E37B63E7E7B504878AE6563347C147F98EF2D*, U3CCompleteOpenU3Ed__24_t4E8DD01DC9B1058D072BBAC6EAD09F2B9E8A0DC3**, MethodInfo const*) (:1090/Build/Build%20Benchmark.wasm)
    at MainMenuScript_Start_mC1D05E15D183A59D0A7AB8AB22E0AA1BBFD1F78F (:1090/Build/Build%20Benchmark.wasm)
    at RuntimeInvoker_TrueVoid_t4861ACF8F4594C3437BB48B6E56783494B843915(void (*)(), MethodInfo const*, void*, void**, void*) (:1090/Build/Build%20Benchmark.wasm)
    at il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) (:1090/Build/Build%20Benchmark.wasm)
    at dynCall_iiii (:1090/Build/Build%20Benchmark.wasm)
    at :1090/Build/Build%20Benchmark.framework.js:1055:20
    at invoke_iiii (:1090/Build/Build%20Benchmark.framework.js:16687:10)
    at il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) (:1090/Build/Build%20Benchmark.wasm)
    at il2cpp_runtime_invoke (:1090/Build/Build%20Benchmark.wasm)
    at ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) (:1090/Build/Build%20Benchmark.wasm)
    at MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr) (:1090/Build/Build%20Benchmark.wasm)
    at MonoBehaviour::DelayedStartCall(Object*, void*) (:1090/Build/Build%20Benchmark.wasm)
    at DelayedCallManager::Update(int) (:1090/Build/Build%20Benchmark.wasm)
    at InitPlayerLoopCallbacks()::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward() (:1090/Build/Build%20Benchmark.wasm)
    at ExecutePlayerLoop(NativePlayerLoopSystem*) (:1090/Build/Build%20Benchmark.wasm)
    at ExecutePlayerLoop(NativePlayerLoopSystem*) (:1090/Build/Build%20Benchmark.wasm)
    at MainLoop() (:1090/Build/Build%20Benchmark.wasm)
    at dynCall_v (:1090/Build/Build%20Benchmark.wasm)
    at :1090/Build/Build%20Benchmark.framework.js:1055:20`
    
    
    `An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it.`

**Comment by caiocabralbr** [comment]
The error is in this line:
`user = await moralis.GetCurrentUserAsync();`

In `MoralisInterface.cs`

**Comment by caiocabralbr** [comment]
Blank Project with v1.0.6 and WebGL build get same error

To reproduce:
Open blank WebGL Unity  2021.2.11f1, add moralis SDK 1.0.6 unitypackage, include the Demo scene and build

**Comment by caiocabralbr** [comment]
Persists in 1.0.4 SDK

**Comment by KoenRijpstra** [comment]
@caiocabralbr Can you check if your Moralis server URI and Moralis Application Id are correct? 

![image](https://user-images.githubusercontent.com/579455/154857657-4f7c02c9-c712-4925-a32d-71ae4a67b494.png)

**Comment by xactant** [comment]
Pulled in updated Wallet Connect which included Koen's pull request.

**Comment by KoenRijpstra** [comment]
@caiocabralbr Can you confirm your issue is solved?
